//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        public int Major_id { get; set; }
        public string Major_Name { get; set; }
        public Nullable<int> Faculity_id { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
