//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_iD { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Employee_id { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
