//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _ASP.NET_MVC_tasks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<int> unitsInStock { get; set; }
        public Nullable<int> Category_id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
